Sprint 12 hw.
Konstantin-Shushkevich/java-filmorate pull request #3
Opened 2024-12-25 12:00 UTC by Konstantin-Shushkevich

Add database

2024-12-28 13:04 UTC, NikolaiDem requested changes

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final JdbcFilmRepository jdbcFilmRepository;
Тип репозитория должен быть интерфейсом, иначе теряется вся гибкость.
Аналогично для всех контроллеров

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/extractor/FilmExtractor.java
> +                genres.add(genre);
А почему только один жанр добавляется? Их не может быть несколько?

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +            Film film = findById(id).orElseThrow(() -> new NotFoundException("Film's id doesn't in database"));
Делать запросы на каждый id выглядит не оптимальным способом, лучше сразу получить все фильмы

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +            user = findById(id).orElseThrow(() -> new NotFoundException("User's id doesn't in database"));
Делать запросы на каждый id выглядит не оптимальным способом, лучше сразу получить всех юзеров

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +    public void addFriend(Integer userId, Integer friendId, boolean status) {
Булева переменная в методе - это code smells. Лучше сделать 2 отдельных метода

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/JdbcUserRepository.java
> +    public void deleteFriend(Integer userId, Integer friendId, boolean status) {
Булева переменная в методе - это code smells. Лучше сделать 2 отдельных метода

2024-12-28 13:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepository.java
> +    void addFriend(Integer userId, Integer friendId, boolean status);
Такой метод выглядит лишним в репозитории. Можно реализовать бизнес логику только с помощью CRUD операций репозитория

2024-12-29 21:28 UTC, Konstantin-Shushkevich commented on src/main/java/ru/yandex/practicum/filmorate/extractor/FilmExtractor.java
> +                genres.add(genre);
Добавляются несколько. Тк после десериализации первой строки и создания экземпляра Film, при десериализации каждой новой строки, при необходимости создается новый объект класса Genre, который добавляется в Set<Genre> genres. После выхода из цикла while, genres добавляется в экземпляр Film через сеттер

2024-12-29 21:31 UTC, Konstantin-Shushkevich commented on src/main/java/ru/yandex/practicum/filmorate/repository/user/UserRepository.java
> +    void addFriend(Integer userId, Integer friendId, boolean status);
Убрал метод из интерфейса, но оставил в jdbc-реализации репозитория. Бизнес-логику по назначению статуса дружбы перенес в сервисный класс. Такое решение приемлемо? Вроде бы так улучшается восприятие кода

2024-12-30 20:45 UTC, NikolaiDem requested changes

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleInternalServerException(final InternalServerException e) {
InternalServerException все же подразумевает какую-то неизвестную ошибку или ошибку, детали которой пользователю не важны. Если причина в невалидности данных, то лучше и создать "говорящее" исключение

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmRepository jdbcFilmRepository;
Ну в названии поля тоже можно убрать конкретную реализацию

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserRepository jdbcUserRepository;
В названии поля лучше удалить jdbc

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/extractor/GenreExtractor.java
> +        if (genre.getId() == 0) {
Почему 0?

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/extractor/RatingMpaExtractor.java
> +        if (ratingMpa.getId() == 0) {
Почему 0?

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/JdbcRatingMpaRepository.java
> +                .map(this::findById)
Лучше сделать метод getByIds, чтобы не идти в бд по каждому запросу

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/repository/film/JdbcFilmRepository.java
> +                jdbcFilms.update(INSERT_VALUES_TO_FILM_GENRE, otherMapSqlParameterSource);
Для множественного обновления лучше использовать batchUpdate

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final JdbcFilmRepository jdbcFilmRepository;
Для типов полей лучше использовать интерфейсы

2024-12-30 20:45 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final JdbcUserRepository jdbcUserRepository;
Для типов полей лучше использовать интерфейсы

2025-01-09 19:13 UTC, merged